parameters:
  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - prod

trigger: none

resources:
  repositories:
  - repository: templates
    type: git
    name: "Shared Services/amn-aws-tf-common-pipelines"

name: amn-aws-tfiac-infra-demo
extends:
  template: templates/extend/infra-foundation-deployment.yml@templates
  parameters:
    vertical: master
    environment: ${{ parameters.environment }}
    ${{ if in(parameters.environment, 'dev')}}:
      resourceFile: environments/dev/dev.tfvars
    ${{ if in(parameters.environment, 'prod')}}:
      resourceFile: environments/dev/prod.tfvars

    