formatter: "md tbl" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

content: |-
  # Introduction 

  __moduleHeader__

  ## Requirements
   - **Terraform**: `~> 1.6`
   - **Provider**: `azurerm ~> 3.71`

  #### Content of the module "main.tf" file.
  ```hcl
  {{ include "main.tf" }}
  ```
  #### This module has the following input variables:  
  {{ .Inputs }}

  #### This module has the following outputs:
  {{ .Outputs }}

  #### The following resources are created by this module:
  
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

 
  ## Example Scenario

  __exampleScenario__

  Random names are generated for the resources to avoid conflicts and ensure unique naming for testing purposes, we have transitioned to using random strings for generating resource names
  #### Contents of the locals.tf file.
  ```hcl
  {{ include "examples/locals.tf" }} 
  ```
  Create below resources for testing purposes.
  ####  Contents of the examples/main.tf file.
  ```hcl
  {{ include "examples/main.tf" }}
  ``` 
  When the Pull Request (PR) pipeline is triggered, the pipeline will first apply input validation unit tests. After successfully validating the inputs, it will proceed to create the necessary resources.   
  It will deploy the resources in T01 environment with below (examples/t01.tfvars) var file.
  #### Contents of the t01.tfvars file.
  ```hcl
  {{ include "examples/t01.tfvars" }}
  ```
  Once the resources are created, the pipeline runs tests to ensure everything is functioning as expected. Upon successful completion of these tests, the pipeline will automatically tear down all the created resources.

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  required-inputs: true
  optional-inputs: true
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true