name: '1.0$(rev:.r)'

resources:
  repositories:
    - repository: amn-az-tf-common-pipelines
      type: git
      name: "Terraform/amn-az-tf-common-pipelines"
    - repository: amn-az-tfm-user-assigned-identity
      type: git
      name: "Terraform/amn-az-tfm-user-assigned-identity"
    - repository: amn-az-tfm-service-bus
      type: git
      name: "Terraform/amn-az-tfm-service-bus"
    - repository: amn-az-tfm-resourcegroup
      type: git
      name: "Terraform/amn-az-tfm-resourcegroup"

variables:
  - name: moduleHeader
    value: "Terraform module to deploy and manage role assignment in Azure."
  
  - name: exampleScenario
    value: "Create role assignment <br /><br /> The following steps in example to using this module:<br /> - Create resource group<br /> - Create role assignment"

  - template: variables/az-tf-module-common-variables.yaml@amn-az-tf-common-pipelines
    parameters:
      repoName: amn-az-tfm-role-assignment

trigger:
  - none

stages:
- template: templates/az-tf-module-pr-template.yaml@amn-az-tf-common-pipelines
  parameters:
    WorkingDirectory: $(workingDirectory)/
    ServiceArm: $(ServiceArm)
    VarFilePath: '"$(workingDirectory)/$(environment)".tfvars'
    TestDirectory: 'tests/apply_validation_tests'
    PoolName: 'shac_linux_infra'
    DependentRepositories:
     - "amn-az-tfm-resourcegroup"
     - "amn-az-tfm-service-bus"
     - "amn-az-tfm-user-assigned-identity"

- stage: RaisePR
  displayName: 'Raise PR to Default Branch'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - template: templates/readme-pr-template.yaml@amn-az-tf-common-pipelines
    parameters:
      TARGET_BRANCH_NAME: 'main'  # Replace with your default branch