name: "1.0$(rev:.r)"

resources:
  repositories:
    - repository: amn-az-tf-common-pipelines
      type: git
      name: "Terraform/amn-az-tf-common-pipelines"
    - repository: amn-az-tfm-resourcegroup
      type: git
      name: "Terraform/amn-az-tfm-resourcegroup"
    - repository: amn-az-tfm-app-service-plan
      type: git
      name: "Terraform/amn-az-tfm-app-service-plan"
    - repository: amn-az-tfm-key-vault
      type: git
      name: "Terraform/amn-az-tfm-key-vault"
    - repository: amn-az-tfm-virtual-network
      type: git
      name: "Terraform/amn-az-tfm-virtual-network"
    - repository: amn-az-tfm-diagnostic-setting
      type: git
      name: "Terraform/amn-az-tfm-diagnostic-setting"

variables:
  - name: moduleHeader
    value: "Terraform module to deploy and manage web app in Azure."
  
  - name: exampleScenario
    value: "Create web app <br /><br /> The following steps in example to using this module:<br /> - Create resource group<br /> - Create app service plan<br /> - Create key vault<br /> - Create virtual network<br /> - Create web app"

  - template: variables/az-tf-module-common-variables.yaml@amn-az-tf-common-pipelines
    parameters:
      repoName: amn-az-tfm-win-web-app

trigger:
  - none

stages:
- template: templates/az-tf-module-pr-template.yaml@amn-az-tf-common-pipelines
  parameters:
    WorkingDirectory: $(workingDirectory)
    ServiceArm: $(ServiceArm)
    VarFilePath: '"$(workingDirectory)/$(environment)".tfvars'
    TestDirectory: "tests/apply_validation_tests"
    PoolName: "shac_linux_infra"
    DependentRepositories:
      - "amn-az-tfm-resourcegroup"
      - "amn-az-tfm-app-service-plan"
      - "amn-az-tfm-key-vault"
      - "amn-az-tfm-virtual-network"
      - "amn-az-tfm-diagnostic-setting"

- stage: RaisePR
  displayName: 'Raise PR to Default Branch'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - template: templates/readme-pr-template.yaml@amn-az-tf-common-pipelines
    parameters:
      TARGET_BRANCH_NAME: 'main'  # Replace with your default branch
