variables:
  AMN_HUB_ResourceGroupName: 'amn-wus2-hub-rg-p01'
  Azure_Resource_Manager_connection : 'AMN_shared_PROD'
  environment : 'PROD'
  location : 'west us 2'
  Subscription : '06ab2c80-382c-478f-bcd5-5e1afe984092'
  Template_Path : '/Artifacts/ARM/Infrastructure'