# Pipeline file structure: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# Task List: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks

name: "2.0$(rev:.r)"

resources:
  - repo : self

trigger:
   batch: true
   branches:
    include:
      - /*
   paths :
    include:
    - src/ARM/Infrastructure/appgateway/*
variables:
 - group: "AMN_IPS_INFRA"

stages:
# ==========================================================================================================================================
- stage : Build
  jobs:
  - template : /Azure-pipelines/build-steps.yml

# ==========================================================================================================================================
- stage : TEST
  displayName: TEST
  dependsOn: Build
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEST_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : TEST_DR
  displayName: TEST_DR
  dependsOn: Build
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEST_DR_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : DEV
  displayName: DEV
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/DEV_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : QA
  displayName: QA
  dependsOn:
  - DEV
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/QA_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}


# ==========================================================================================================================================
- stage : TEAM_A
  displayName: TEAM_A
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEAM_A_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : TEAM_B
  displayName: TEAM_B
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEAM_B_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : TEAM_C
  displayName: TEAM_C
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEAM_C_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : TEAM_D
  displayName: TEAM_D
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEAM_D_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : TEAM_E
  displayName: TEAM_E
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TEAM_E_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}

# ==========================================================================================================================================
- stage : TRAIN
  displayName: TRAIN
  dependsOn:
  - TEST
  - TEST_DR
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'), startsWith(variables['Build.SourceBranch'], 'refs/heads/story/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  variables :
  - template : /Azure-pipelines/Variables/TRAIN_variables.yaml
  jobs :
  - deployment: appgwmanagedIDDeployment
    displayName: Appgateway ManagedID Deployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agwmanagedID.template.json'
               resource_param_name : 'agwmanagedID.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}
               
  - deployment: appgwdeployment
    displayName: Appgateway Deployment
    dependsOn: appgwmanagedIDDeployment
    workspace:
      clean: all 
    environment :  ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - template :  /Azure-pipelines/release-steps.yml
            parameters:
               resource_name : 'appgateway'
               resource_template_name : 'agw.template.json'
               resource_param_name : 'agw.parameters.json'
               environment : ${{ variables.environment }}
               Azure_Resource_Manager_connection : ${{ variables.Azure_Resource_Manager_connection }}